INSERT INTO dbdress.store_supporting_documents (store_id,ktp,siup,npwp,skdp,tdp,created_at,updated_at) VALUES 
(1000,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1001,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1002,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1003,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1004,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1005,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1006,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
;
INSERT INTO dbdress.store_supporting_documents (store_id,ktp,siup,npwp,skdp,tdp,created_at,updated_at) VALUES 
(1007,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1008,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1009,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1010,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1011,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1012,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1013,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1014,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1015,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1016,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
;
INSERT INTO dbdress.store_supporting_documents (store_id,ktp,siup,npwp,skdp,tdp,created_at,updated_at) VALUES 
(1017,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1018,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1019,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1020,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1021,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1022,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1023,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1024,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1025,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1026,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
;
INSERT INTO dbdress.store_supporting_documents (store_id,ktp,siup,npwp,skdp,tdp,created_at,updated_at) VALUES 
(1027,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1028,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1029,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1030,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1031,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1032,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1033,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1034,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1035,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1036,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
;
INSERT INTO dbdress.store_supporting_documents (store_id,ktp,siup,npwp,skdp,tdp,created_at,updated_at) VALUES 
(1037,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1038,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1039,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1040,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1041,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1042,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1043,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1044,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1045,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(1046,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
;
INSERT INTO dbdress.store_supporting_documents (store_id,ktp,siup,npwp,skdp,tdp,created_at,updated_at) VALUES 
(1047,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
;